# Generated by Django 3.2.16 on 2023-12-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_congratulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congratulation',
            name='text',
            field=models.TextField(verbose_name='Текст поздравления'),
        ),
    ]
